version: "3"
services:
  musiphone:
    container_name: musiphone
    image: ortexx/musiphone
    restart: on-failure
    env_file:
      ./.env
    environment:
      MUSIPHONE_FACE: $MUSIPHONE_FACE
      MUSIPHONE_HOSTNAME: $MUSIPHONE_HOSTNAME
      MUSIPHONE_PORT: $MUSIPHONE_PORT
      MUSIPHONE_PUBLIC_PORT: $MUSIPHONE_PUBLIC_PORT 
      MUSIPHONE_PLAYLIST_MAX_SIZE: $MUSIPHONE_PLAYLIST_MAX_SIZE 
      MUSIPHONE_COLLECTION_MAX_SIZE: $MUSIPHONE_COLLECTION_MAX_SIZE 
      MUSIPHONE_MUSIC_STORAGE_ADDRESS: $MUSIPHONE_MUSIC_STORAGE_ADDRESS
      MUSIPHONE_INITIAL_NETWORK_ADDRESS: $MUSIPHONE_INITIAL_NETWORK_ADDRESS
      MUSIPHONE_LOGGER_LEVEL: $MUSIPHONE_LOGGER_LEVEL
      MUSIPHONE_STORAGE_PATH: $MUSIPHONE_STORAGE_PATH
    ports:
      - $MUSIPHONE_DOCKER_PORT:$MUSIPHONE_PORT
    volumes:
      - $MUSIPHONE_STORAGE_PATH:/usr/src/app/musiphone